### ISSUE TITLE
Support more video addons

### ISSUE THREAD

**Issue by TwilightMercy** [dimkroon/translate_subs#11]
Hi,

Can you provide full details on how to implement to other video addons support the addon?

**Comment by dimkroon** [comment]
Thanks for your interest @TwilightMercy .
You're right, I should write a wiki page on that some time, but the add-on in still experimental, so it may be a bit early for that.
You  are of course very welcome to join the experiment and I'm very interested to hear if/how this works in other add-ons.

Video add-ons that provide subtitles for a particular video by way of a downloadable file can offer these for translation by simply adding a few properties to the resolved Listitem. If a user has TranslateSubs installed it will read these properties the moment a video starts and will try to translate the subtitles. When TranslateSubs is not installed these properties will simple have no effect.

Currently, these properties are supported:

#### subtitles.translate.file
The path to the downloaded subtitles file in a format that xmbcvfs.File() can open. Or an HTTP(S) url that can be opened by a plain GET request.

#### subtitles.translate.type
Optional. The type (file extension) of the subtitles file. If absent the type will be derived from the file name.

#### subtitles.translate.orig_lang
Optional. The 2-letter  language code of the subtitles in the file. If absent, TranslateSubs will try to derive the language from the filename if that name is in a format like 'video_name.lang.extention', e.g. 'hearing impaired.en.srt'. If the original language remains unknown, or is specifically set to 'auto' the translating service is asked to auto detect the original language.
Since video add-on usually already know the language of their subtitles, it would take out a lot guessing if they could provided this property.

#### subtitles.translate.filter_flags
Optional. A bitmask indicating what filters to apply to the subtitles. Is bound to change, so probably best not to use it right now.

#### subtitles.translate.video_id
Optional. Will probably be renamed to subtitle_id in the near future. 
Is a string that uniquely identifies the video (or subtitle file). Is used to cache translated subs and use the cached version when the stream is played again. Care must be taken that this string is unique to the video(or subtitle), but is the same each time the video is played. 
If not given, the path (url) of the video is taken without a possible query string. If this is not enough to a uniquely identify your stream, set one using this property. Often the original url to the subtitle is fine, or create one by concatenating the add-on id and id of the video.

As a example you could have a look at [how it's done in viwX](https://github.com/dimkroon/itvx-for-kodi/blob/fd7dbdb85f56c22bf57f8d17e16c47c52701f483/plugin.video.viwx/resources/lib/main.py#L588).

TranslateSubs only accepts subtitles in srt, ttml and web vtt format. but operates internally on srt, so that is the preferred format. It has a pretty decent converter for vtt, but ttml conversion is very basic.

**Comment by TwilightMercy** [comment]
Why don't you implement the addon as a standalone subtitles addon, that doesn't depends on other addons specific implementations?

You can get all metadata through Kodi info tags params, and search accordingly subtitles to translate. Just like any other subtitles addon, for example a4kSubtitles

**Comment by dimkroon** [comment]
I would if I knew how. Please let me know how get all required data from info tags.

Other subtitles add-on search and download subtitle from a web service based on info like video title, which is very different to translating existing files.

Maybe the attempts at the branch feature/manual-translation comes closer to what you mean? Discussed [here](https://github.com/dimkroon/translate_subs/discussions/9#discussioncomment-9769408)

**Comment by TwilightMercy** [comment]
Take a look on this a4ksubtitles example:

https://github.com/a4k-openproject/a4kSubtitles/blob/master/a4kSubtitles/api.py#L28

The subtitles addon get the playing metadata on video playback
Then it uses the metadata (IMDB ID, title, etc..) to search subtitles on some websites (For example: OpenSubtitles),
then shows the results in Kodi's subtitle dialog.nt!
TO
